SConscript(['common/SConscript',
						'light/SConscript',
						'vis/SConscript',
						'qbsp/SConscript',
						'bspinfo/SConscript',
						'qfiles/SConscript',
						'qcc/SConscript',
#						'sprgen/SConscript',
#						'modelgen/SConscript',
])
