Import( 'env' )
myenv=env.Copy()

myenv['CPPPATH'] = '../common'
myenv['LIBS'] = Split('qutils m bsp')
myenv['LIBPATH'] = '../common'

files = Split('threads.c entities.c light.c ltface.c trace.c')
myenv.Program('light', files)

