env = Environment()
env['CPPPATH'] = '../common'
env['LIBS'] = Split('qutils m bsp')
env['LIBPATH'] = '../common'

files = Split('threads.c entities.c light.c ltface.c trace.c')
env.Program('light', files)

