Import( 'env installPath' )
myenv=env.Copy()

myenv['CPPPATH'] = '../common'
myenv['LIBS'] = Split('qutils m bsp')
myenv['LIBPATH'] = '../common'

files = Split('threads.c entities.c light.c ltface.c trace.c')
light = myenv.Program('light', files)

myenv.Install(installPath, light)
