Import('env')
myenv=env.Copy()

myenv['CPPPATH'] = '../common'
myenv['LIBS'] = Split('qutils m bsp')
myenv['LIBPATH'] = '../common'

files=['brush.c', 'csg4.c', 'map.c', 'merge.c', 'nodraw.c', 'outside.c', 'portals.c', 'qbsp.c', 'region.c', 'solidbsp.c', 'surfaces.c', 'tjunc.c', 'writebsp.c']
myenv.Program('qbsp', files) 

