Import( 'env' )
myenv=env.Copy()

myenv['CCFLAGS'] += ' -fno-common'

myenv.StaticLibrary('wad', 'wadlib.c')
myenv.StaticLibrary('scrip', 'scriplib.c')
myenv.StaticLibrary('bsp', 'bspfile.c')
myenv.StaticLibrary('qutils', Split('cmdlib.c lbmlib.c mathlib.c polylib.c threads.c trilib.c'))
