Import('env installPath')
myenv=env.Copy()

myenv['CPPPATH'] = '../common'
myenv['LIBS'] = Split('qutils m bsp')
myenv['LIBPATH'] = '../common'

vis = myenv.Program('vis', ['flow.c', 'soundpvs.c', 'vis.c'])  
myenv.Install(installPath, vis)
