Import('env')
myenv=env.Copy()

myenv['CPPPATH'] = '../common'
myenv['LIBS'] = Split('qutils scrip wad m')
myenv['LIBPATH'] = '../common'

files = Split('qlumpy.c  quakegrb.c')
myenv.Program('qlumpy', files)

